---
- hosts: all
  name: Setup Laptop
  vars:
    setup_cargo: "{{ cargo | default('false') }}"
    setup_sdkman: "{{ sdkman | default('false') }}"
    setup_nvm: "{{ nvm | default('false') }}"
    setup_docker: "{{ docker | default('false') }}"
  roles:
    - common
    - role: cargo
      when: setup_cargo == 'true'
    - role: sdkman
      when: setup_sdkman == 'true'
    - role: nodejs
      when: setup_nvm == 'true'
    - role: docker
      when: setup_docker == 'true'
